import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),dir=path.join(root,'assets','siena_npc');
const manifest=JSON.parse(fs.readFileSync(path.join(dir,'asset-manifest.json'),'utf8'));
const tweak=fs.readFileSync(path.join(dir,manifest.tweakxl_source),'utf8');
const project=fs.readFileSync(path.resolve(dir,manifest.wolvenkit_project),'utf8');
const projectTweak=fs.readFileSync(path.resolve(dir,manifest.wolvenkit_tweakxl_source),'utf8');
const sourceEntity=path.join(root,'wolvenkit','siena_npc','source','archive',...manifest.source_entity_path.split('/')),sourceAppearance=path.join(root,'wolvenkit','siena_npc','source','archive',...manifest.source_appearance_path.split('/'));
const entityPath=path.resolve(dir,manifest.wolvenkit_entity_source),appearancePath=path.resolve(dir,manifest.wolvenkit_appearance_source),packedRoot=path.resolve(dir,manifest.packed_archive_search_root);
if(manifest.record!=='Siena.SienaCompanion'||manifest.appearance!=='siena_default')throw new Error('stable Siena identity mismatch');
if(manifest.package_version!=='0.10.0'||manifest.stable_tweakdb_record!==manifest.record)throw new Error('package version or stable record mismatch');
if(manifest.source_entity_path!=='ep1/characters/entities/citizen/citizen__ep1_rich_wa.ent'||manifest.source_appearance_path!=='base/characters/appearances/citizen/citizen__rich_wa.app'||manifest.source_entity_appearance_display!=='citizen__rich_wa_rich_23_casual'||manifest.source_appearance_name!=='rich_23_casual')throw new Error('confirmed source contract changed');
for(const file of [sourceEntity,sourceAppearance])if(!fs.existsSync(file)||fs.readFileSync(file).subarray(0,4).toString('ascii')!=='CR2W')throw new Error(`confirmed source CR2W missing/invalid: ${file}`);
if(!/^Siena\.SienaCompanion:/m.test(tweak)||!/^\s+\$base: Character\.CitizenRichFemaleCasual$/m.test(tweak))throw new Error('TweakXL record source invalid');
if(!/<CP77Mod[\s>]/.test(project)||!/<Name>siena_npc<\/Name>/.test(project))throw new Error('WolvenKit cpmodproj invalid');
for(const text of [tweak,projectTweak]){
  if(!/^Siena\.SienaCompanion:\s*\r?\n\s+\$base: Character\.CitizenRichFemaleCasual\s*\r?\n\s+entityTemplatePath: siena\\entities\\siena_default\.ent\s*\r?\n\s+appearanceName: siena_default$/m.test(text))throw new Error('deployment and WolvenKit TweakXL records differ');
}
if(/PlayerPuppet|Character\.(judy|panam|songbird|rogue)/i.test(tweak))throw new Error('quest or player dependency forbidden');
for(const key of ['entity_resource','appearance_resource'])if(!/^[a-z0-9_\-/]+\.(ent|app)$/i.test(manifest[key]))throw new Error(`${key} invalid`);
if(manifest.entity_resource!=='siena/entities/siena_default.ent'||manifest.appearance_resource!=='siena/appearances/siena_default.app')throw new Error('Siena-owned depot paths changed');
if(manifest.archive_xl_required!==false)throw new Error('Stage A must not claim an unneeded ArchiveXL mapping');
for(const file of [entityPath,appearancePath])if(fs.existsSync(file)&&fs.readFileSync(file).subarray(0,4).toString('ascii')!=='CR2W')throw new Error(`fake/non-CR2W binary resource: ${file}`);
const wscript=fs.readFileSync(path.join(root,'wolvenkit','siena_npc','scripts','CreateSienaStandaloneAssets.wscript'),'utf8');
if(!wscript.includes("BASE_ENTITY_PATH = 'ep1\\\\characters\\\\entities\\\\citizen\\\\citizen__ep1_rich_wa.ent'")||!wscript.includes('GetFileFromProject')||!wscript.includes('SAFE_REPLACE = false')||!wscript.includes('FileExistsInProject(destination)'))throw new Error('safe WolvenKit authoring guard missing');
const deploy=fs.readFileSync(path.join(root,'scripts','deploy_siena_embodied_companion.ps1'),'utf8');
const rollback=fs.readFileSync(path.join(root,'scripts','uninstall_siena_embodied_companion.ps1'),'utf8');
const validator=fs.readFileSync(path.join(root,'scripts','validate_siena_wolvenkit_assets.ps1'),'utf8');
for(const evidence of ['Close Cyberpunk 2077','Required runtime dependency missing','missing authored/build resource','$Entity,$Appearance','Expected exactly one WolvenKit packed siena_npc.archive','BackupRoot','deployment.json','Post-copy hash verification failed','Deployment failed and prior Siena paths were restored','Duplicate active Siena package','Backup content exists inside an active mod directory'])if(!deploy.includes(evidence))throw new Error(`deployment safety evidence missing: ${evidence}`);
for(const evidence of ['Rollback manifest belongs to another game root','Rollback manifest contains an unowned target','Restore/remove Siena-owned deployment path'])if(!rollback.includes(evidence))throw new Error(`rollback safety evidence missing: ${evidence}`);
for(const evidence of ['8EECF5884FD0AAB60AA652953250F68ECD0A77C26E38307DD6D072ED34B60E56','4C437D28462DAC23BF8863EEA0501CD2FD9FDC593477166A14981FDBB6AC249A','Canonical TweakXL source must contain exactly one','conflicting authored definition','generated/output copy is not a competing source','WolvenKit GUI File Validation'])if(!validator.includes(evidence))throw new Error(`asset validator evidence missing: ${evidence}`);
if(manifest.binary_asset_status!=='manual_wolvenkit_build_required')throw new Error('binary asset status must remain honest');
for(const key of ['binary_authoring_completed','binary_validation_completed','packed_archive_completed','live_validation_completed'])if(manifest[key]!==false)throw new Error(`${key} cannot be true before evidence exists`);
const archives=fs.existsSync(packedRoot)?fs.readdirSync(packedRoot,{recursive:true}).filter(name=>path.basename(name)==='siena_npc.archive'):[];
const missing=[entityPath,appearancePath,...(archives.length===1?[]:[path.join(packedRoot,'**','siena_npc.archive')])].filter(file=>!fs.existsSync(file));
console.log(`Siena asset preparation checks passed; authoring readiness blockers: ${missing.length ? missing.join(', ') : 'none'}.`);
