[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$GamePath,[string]$BackupRoot)
$ErrorActionPreference='Stop'
if(Get-Process -Name 'Cyberpunk2077' -ErrorAction SilentlyContinue){throw 'Close Cyberpunk 2077 before deployment.'}
$Root=Split-Path -Parent $PSScriptRoot;$Game=[IO.Path]::GetFullPath($GamePath).TrimEnd('\')
$BackupRoot=if($BackupRoot){[IO.Path]::GetFullPath($BackupRoot)}else{Join-Path $Root '.deployment_backups'}
if(-not(Test-Path -LiteralPath (Join-Path $Game 'bin\x64\Cyberpunk2077.exe') -PathType Leaf)){throw "Invalid game root: $Game"}
$Dependencies=@((Join-Path $Game 'red4ext\red4ext.dll'),(Join-Path $Game 'red4ext\plugins\TweakXL\TweakXL.dll'),(Join-Path $Game 'red4ext\plugins\Codeware\Codeware.dll'),(Join-Path $Game 'bin\x64\plugins\cyber_engine_tweaks.asi'))
foreach($Dependency in $Dependencies){if(-not(Test-Path -LiteralPath $Dependency -PathType Leaf)){throw "Required runtime dependency missing: $Dependency"}}
$Project=Join-Path $Root 'wolvenkit\siena_npc\siena_npc.cpmodproj';$Entity=Join-Path $Root 'wolvenkit\siena_npc\source\archive\siena\entities\siena_default.ent';$Appearance=Join-Path $Root 'wolvenkit\siena_npc\source\archive\siena\appearances\siena_default.app';$PackedRoot=Join-Path $Root 'wolvenkit\siena_npc\packed';$CanonicalTweak=Join-Path $Root 'assets\siena_npc\source\r6\tweaks\siena_npc.yaml';$Controller=Join-Path $Root 'bridge\cet\siena_npc_controller'
$PackedTweaks=@(Get-ChildItem -LiteralPath $PackedRoot -Recurse -File -Filter 'siena_npc.yaml' -ErrorAction SilentlyContinue|Where-Object{$_.FullName-match'[\\/]r6[\\/]tweaks[\\/]'});if($PackedTweaks.Count-gt1){throw 'Multiple packed Siena TweakXL files found.'};$Tweak=if($PackedTweaks.Count-eq1){$PackedText=(Get-Content -LiteralPath $PackedTweaks[0].FullName -Raw)-replace"`r`n","`n";$CanonicalText=(Get-Content -LiteralPath $CanonicalTweak -Raw)-replace"`r`n","`n";if($PackedText.Trim()-ne$CanonicalText.Trim()){throw 'Packed and canonical TweakXL files differ.'};$PackedTweaks[0].FullName}else{$CanonicalTweak}
foreach($Required in $Project,$Entity,$Appearance,$Tweak,(Join-Path $Controller 'manifest.json')){if(-not(Test-Path -LiteralPath $Required -PathType Leaf)){throw "v0.10.0 preflight refused deployment; missing authored/build resource: $Required"}}
$Archives=@(Get-ChildItem -LiteralPath $PackedRoot -Recurse -File -Filter 'siena_npc.archive' -ErrorAction SilentlyContinue);if($Archives.Count-ne1){throw "Expected exactly one WolvenKit packed siena_npc.archive under $PackedRoot; found $($Archives.Count). Pack Project has not been proven."};$Archive=$Archives[0].FullName;$ArchiveXlCandidate=@(Get-ChildItem -LiteralPath $PackedRoot -Recurse -File -Filter 'siena_npc.archive.xl' -ErrorAction SilentlyContinue);if($ArchiveXlCandidate.Count-gt1){throw 'Multiple packed ArchiveXL control files found.'};$ArchiveXl=if($ArchiveXlCandidate.Count-eq1){$ArchiveXlCandidate[0].FullName}else{Join-Path $PackedRoot '__not_required__.archive.xl'}
foreach($Cr2w in $Entity,$Appearance){$Bytes=[IO.File]::ReadAllBytes($Cr2w);if($Bytes.Length-lt16-or[Text.Encoding]::ASCII.GetString($Bytes,0,4)-ne'CR2W'){throw "Invalid or fake CR2W resource: $Cr2w"}}
if((Get-Item -LiteralPath $Archive).Length-lt1024){throw "Built archive is unexpectedly small: $Archive"}
$ProjectText=Get-Content -LiteralPath $Project -Raw;$TweakText=Get-Content -LiteralPath $Tweak -Raw;$ControllerText=(Get-Content -LiteralPath (Join-Path $Controller 'config.lua') -Raw)+(Get-Content -LiteralPath (Join-Path $Controller 'npc_entity.lua') -Raw)
if($ProjectText-notmatch'<Name>siena_npc</Name>'){throw 'Unexpected WolvenKit project identity.'}
if($TweakText-notmatch'Siena\.SienaCompanion'-or$TweakText-notmatch'entityTemplatePath:\s*siena\\entities\\siena_default\.ent'-or$TweakText-notmatch'appearanceName:\s*siena_default'){throw 'Production TweakXL record does not reference Siena-owned resources.'}
if($ControllerText-notmatch'entity_record\s*=\s*"Siena\.SienaCompanion"'-or$ControllerText-match'TweakDBID\.new\("Character\.CitizenRichFemaleCasual"\)'){throw 'Production controller record boundary failed.'}
$ModsRoot=Join-Path $Game 'bin\x64\plugins\cyber_engine_tweaks\mods';$ArchiveRoot=Join-Path $Game 'archive\pc\mod';$TweakParent=Join-Path $Game 'r6\tweaks'
$DuplicateCet=@(Get-ChildItem -LiteralPath $ModsRoot -Directory -ErrorAction SilentlyContinue|Where-Object{$_.Name-match'(?i)siena.*npc|npc.*siena'}|Where-Object{$_.Name-ne'siena_npc_controller'});$DuplicateArchives=@(Get-ChildItem -LiteralPath $ArchiveRoot -File -ErrorAction SilentlyContinue|Where-Object{$_.Name-match'(?i)siena.*npc.*\.(archive|xl)$'}|Where-Object{$_.Name-notin @('siena_npc.archive','siena_npc.archive.xl')});$DuplicateTweaks=@(Get-ChildItem -LiteralPath $TweakParent -Directory -ErrorAction SilentlyContinue|Where-Object{$_.Name-match'(?i)siena.*npc|npc.*siena'}|Where-Object{$_.Name-ne'siena_npc'})
if($DuplicateCet.Count+$DuplicateArchives.Count+$DuplicateTweaks.Count-gt0){throw 'Duplicate active Siena package detected; resolve it manually before deployment.'}
$ActiveBackups=@(Get-ChildItem -LiteralPath $ModsRoot,$ArchiveRoot,$TweakParent -Recurse -Force -ErrorAction SilentlyContinue|Where-Object{$_.Name-match'(?i)(^|[._-])(backup|bak)([._-]|$)|deployment_backups'});if($ActiveBackups.Count){throw 'Backup content exists inside an active mod directory; move it outside the game tree before deployment.'}
$Backup=Join-Path $BackupRoot (Get-Date -Format 'yyyyMMdd-HHmmss');$Data=Join-Path $Backup 'data';New-Item -ItemType Directory -Path $Data -Force|Out-Null
$Targets=@(@{Key='cet';Path=(Join-Path $ModsRoot 'siena_npc_controller');Source=$Controller;Directory=$true},@{Key='tweak';Path=(Join-Path $TweakParent 'siena_npc');Source=(Split-Path -Parent $Tweak);Directory=$true},@{Key='archive';Path=(Join-Path $ArchiveRoot 'siena_npc.archive');Source=$Archive;Directory=$false},@{Key='archive_xl';Path=(Join-Path $ArchiveRoot 'siena_npc.archive.xl');Source=$ArchiveXl;Directory=$false})
$Entries=@();foreach($Item in $Targets){$Exists=Test-Path -LiteralPath $Item.Path;$Saved=Join-Path $Data $Item.Key;if($Exists){Copy-Item -LiteralPath $Item.Path -Destination $Saved -Recurse -Force};$Entries+=[pscustomobject]@{key=$Item.Key;target=$Item.Path;backup=$Saved;existed=$Exists;directory=$Item.Directory}}
[pscustomobject]@{version='0.10.0';game_root=$Game;created_at=(Get-Date).ToString('o');entries=$Entries}|ConvertTo-Json -Depth 5|Set-Content -LiteralPath (Join-Path $Backup 'deployment.json') -Encoding UTF8
try{
  foreach($Item in $Targets){if(Test-Path -LiteralPath $Item.Path){Remove-Item -LiteralPath $Item.Path -Recurse -Force};if($Item.Key-eq'archive_xl'-and-not(Test-Path -LiteralPath $ArchiveXl)){continue};$Parent=Split-Path -Parent $Item.Path;New-Item -ItemType Directory -Path $Parent -Force|Out-Null;if($Item.Directory){Copy-Item -LiteralPath $Item.Source -Destination $Item.Path -Recurse -Force}else{Copy-Item -LiteralPath $Item.Source -Destination $Item.Path -Force}}
  $HashPairs=@([pscustomobject]@{Source=$Archive;Target=(Join-Path $ArchiveRoot 'siena_npc.archive')},[pscustomobject]@{Source=$Tweak;Target=(Join-Path $TweakParent 'siena_npc\siena_npc.yaml')},[pscustomobject]@{Source=(Join-Path $Controller 'manifest.json');Target=(Join-Path $ModsRoot 'siena_npc_controller\manifest.json')})
  if(Test-Path -LiteralPath $ArchiveXl){$HashPairs+=[pscustomobject]@{Source=$ArchiveXl;Target=(Join-Path $ArchiveRoot 'siena_npc.archive.xl')}}
  foreach($Pair in $HashPairs){if(-not(Test-Path -LiteralPath $Pair.Target -PathType Leaf)-or(Get-FileHash -Algorithm SHA256 -LiteralPath $Pair.Source).Hash-ne(Get-FileHash -Algorithm SHA256 -LiteralPath $Pair.Target).Hash){throw "Post-copy hash verification failed: $($Pair.Target)"}}
}catch{
  foreach($Entry in $Entries){if(Test-Path -LiteralPath $Entry.target){Remove-Item -LiteralPath $Entry.target -Recurse -Force};if($Entry.existed){New-Item -ItemType Directory -Path (Split-Path -Parent $Entry.target) -Force|Out-Null;Copy-Item -LiteralPath $Entry.backup -Destination $Entry.target -Recurse -Force}}
  throw "Deployment failed and prior Siena paths were restored from $Backup. $($_.Exception.Message)"
}
Write-Host "v0.10.0 deployed from prebuilt WolvenKit output. Rollback backup: $Backup"
Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $ArchiveRoot 'siena_npc.archive'),(Join-Path $TweakParent 'siena_npc\siena_npc.yaml')|Format-Table -AutoSize
