[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$GamePath,[string]$BackendUrl='http://127.0.0.1:8765')
$ErrorActionPreference='Stop';$Root=Split-Path -Parent $PSScriptRoot;$Game=[IO.Path]::GetFullPath($GamePath).TrimEnd('\')
if(Get-Process -Name 'Cyberpunk2077' -ErrorAction SilentlyContinue){throw 'Close Cyberpunk 2077 before file verification.'}
$Source=Join-Path $Root 'bridge\cet\siena_npc_controller';$Target=Join-Path $Game 'bin\x64\plugins\cyber_engine_tweaks\mods\siena_npc_controller'
$Manifest=Get-Content -LiteralPath (Join-Path $Target 'manifest.json') -Raw|ConvertFrom-Json;if($Manifest.version-ne'0.10.0'){throw 'Installed CET controller is not v0.10.0.'}
foreach($File in Get-ChildItem -LiteralPath $Source -File|Where-Object{$_.Extension -in '.lua','.json','.md'}){$Installed=Join-Path $Target $File.Name;if(-not(Test-Path -LiteralPath $Installed)-or(Get-FileHash $File.FullName).Hash-ne(Get-FileHash $Installed).Hash){throw "CET hash mismatch: $($File.Name)"}}
$Tweak=Join-Path $Game 'r6\tweaks\siena_npc\siena_npc.yaml';$Archive=Join-Path $Game 'archive\pc\mod\siena_npc.archive';$PackedRoot=Join-Path $Root 'wolvenkit\siena_npc\packed';$Entity=Join-Path $Root 'wolvenkit\siena_npc\source\archive\siena\entities\siena_default.ent';$Appearance=Join-Path $Root 'wolvenkit\siena_npc\source\archive\siena\appearances\siena_default.app';$Built=@(Get-ChildItem -LiteralPath $PackedRoot -Recurse -File -Filter 'siena_npc.archive' -ErrorAction SilentlyContinue);if($Built.Count-ne1){throw 'Expected exactly one packed Siena archive.'};$BuiltArchive=$Built[0].FullName
foreach($Required in $Tweak,$Archive,$BuiltArchive,$Entity,$Appearance){if(-not(Test-Path -LiteralPath $Required -PathType Leaf)){throw "Required authored/deployed asset missing: $Required"}}
$TweakText=Get-Content -LiteralPath $Tweak -Raw;if($TweakText-notmatch'Siena\.SienaCompanion'-or$TweakText-notmatch'siena\\entities\\siena_default\.ent'-or$TweakText-notmatch'appearanceName:\s*siena_default'){throw 'Stable Siena TweakXL record does not reference Siena-owned assets.'}
if((Get-FileHash -LiteralPath $Archive).Hash-ne(Get-FileHash -LiteralPath $BuiltArchive).Hash){throw 'Installed archive hash differs from WolvenKit build output.'}
$Active=Get-ChildItem -LiteralPath (Join-Path $Game 'bin\x64\plugins\cyber_engine_tweaks\mods') -Directory|Where-Object{$_.Name-match'(?i)siena.*npc|npc.*siena'};if(@($Active).Count-ne1){throw 'Expected exactly one active Siena NPC CET folder.'}
$ActiveArchives=@(Get-ChildItem -LiteralPath (Join-Path $Game 'archive\pc\mod') -File|Where-Object{$_.Name-match'(?i)siena.*npc.*\.archive$'});$ActiveTweaks=@(Get-ChildItem -LiteralPath (Join-Path $Game 'r6\tweaks') -Directory|Where-Object{$_.Name-match'(?i)siena.*npc|npc.*siena'});if($ActiveArchives.Count-ne1-or$ActiveArchives[0].Name-ne'siena_npc.archive'-or$ActiveTweaks.Count-ne1-or$ActiveTweaks[0].Name-ne'siena_npc'){throw 'Duplicate or unexpected active Siena asset package detected.'}
$Config=Get-Content -LiteralPath (Join-Path $Target 'config.lua') -Raw;if($Config-notmatch'entity_record\s*=\s*"Siena\.SienaCompanion"'-or$Config-notmatch'npc_presence_enabled\s*=\s*false'-or$Config-notmatch'npc_auto_spawn\s*=\s*false'-or$Config-notmatch'rescue_enabled\s*=\s*false'){throw 'Controller identity or safe defaults changed.'}
$Health=Invoke-RestMethod ($BackendUrl.TrimEnd('/')+'/health') -TimeoutSec 2;$Status=Invoke-RestMethod ($BackendUrl.TrimEnd('/')+'/api/v1/npc/status') -TimeoutSec 2
if($Health.version-ne'0.10.0'-or$Status.enabled-ne$true){throw 'Backend v0.10.0 embodiment service must be running with NPC controller enabled.'}
Write-Host 'v0.10.0 deployment hashes, stable record, single folder, safe defaults and backend service verified.'
