import {useEffect,useMemo,useState} from 'react'
import {useObserver} from './useObserver'
import {useVoicePlayback} from './useVoicePlayback'
import {lifecycleCanReplace,selectLiveReaction} from './reactionView'
import {formatCyberdeck,formatResource,shortenWeaponRecord} from './deepGameStateView'
import type {BridgeCapabilities,Intent,Priority,ReactionGenerationStatus,ReactionProviderStatus,SceneContext,SienaReaction,VoiceClipReady,VoiceGenerationStatus} from './types'

const priorities:Priority[]=['P0_CRITICAL','P1_HIGH','P2_MEDIUM','P3_LOW']
const intents:Intent[]=['follow','hold','regroup','protect','retreat','stop']
const HISTORY_PREVIEW=8
const yes=(value:boolean)=>value?'YES':'NO'
const percent=(value:number,max:number)=>max>0?Math.round(value/max*100):0

function Card({title,children,className=''}:{title:string;children:React.ReactNode;className?:string}){return <section className={`card ${className}`}><h2>{title}</h2>{children}</section>}
function Row({label,value,hot=false}:{label:string;value:React.ReactNode;hot?:boolean}){return <div className="row"><span>{label}</span><strong className={hot?'hot':''}>{value}</strong></div>}

function ReactionMeta({reaction}:{reaction:SienaReaction}){
  if(reaction.fallback_used)return <small>Template fallback · Core недоступен</small>
  const provider=reaction.provider==='siena_core'?'Siena Core':reaction.provider
  const latency=reaction.latency_ms==null?'':` · ${(reaction.latency_ms/1000).toFixed(1)} с`
  return <small>{provider}{reaction.model?` · ${reaction.model}`:''}{latency}</small>
}
function SceneTags({phase,focus}:{phase:string|null|undefined;focus:string|null|undefined}){return phase||focus?<div className="scene-tags">{phase&&<span>{phase.replaceAll('_',' ')}</span>}{focus&&<span>{focus.replaceAll('_',' ')}</span>}</div>:null}

function LiveReaction({
  sessionId,reaction,lifecycle,provider,showLifecycle,sessionEnded,scene,voiceGeneration,playingVoice,
}:{
  sessionId:string|null;reaction:SienaReaction|null;lifecycle:ReactionGenerationStatus|null
  provider:ReactionProviderStatus|null;showLifecycle:boolean;sessionEnded:boolean;scene:SceneContext|null
  voiceGeneration:VoiceGenerationStatus|null;playingVoice:VoiceClipReady|null
}){
  if(provider&&!provider.enabled)return <Card title="Live Siena Reaction" className="live-reaction muted"><h3>Реакции отключены</h3><p>Телеметрия и игровые события продолжают работать.</p></Card>
  if(showLifecycle&&lifecycle?.state==='queued')return <Card title="Live Siena Reaction" className="live-reaction pending"><SceneTags phase={lifecycle.scene_phase??scene?.phase} focus={lifecycle.focus}/><h3>Сиена заметила событие</h3><p>Реакция ожидает обработки…</p><div className="typing"><i/><i/><i/></div></Card>
  if(showLifecycle&&lifecycle?.state==='generating')return <Card title="Live Siena Reaction" className="live-reaction pending"><SceneTags phase={lifecycle.scene_phase??scene?.phase} focus={lifecycle.focus}/><h3>Сиена формулирует реакцию…</h3><div className="typing"><i/><i/><i/></div></Card>
  if(reaction){const voiceState=playingVoice?.reaction_id===reaction.reaction_id?'playing':voiceGeneration?.reaction_id===reaction.reaction_id?voiceGeneration.state:null;return <Card title="Live Siena Reaction" className={`live-reaction ${reaction.priority}`}><SceneTags phase={reaction.scene_phase??scene?.phase} focus={reaction.focus}/><p className="reaction-copy">{reaction.text}</p>{voiceState&&<span className={`voice-indicator ${voiceState}`}>🔊 {voiceState.replaceAll('_',' ')}</span>}<ReactionMeta reaction={reaction}/>{reaction.fallback_used&&<span className="fallback-badge">TEMPLATE FALLBACK</span>}{sessionEnded&&<span className="session-state">Сессия завершена</span>}</Card>}
  if(provider?.configured_provider==='siena_core'&&(provider.configuration_error||provider.siena_core_reachable===false))return <Card title="Live Siena Reaction" className="live-reaction muted"><h3>Сиена временно недоступна</h3><p>Игровое наблюдение продолжается. Используются резервные реакции.</p></Card>
  return <Card title="Live Siena Reaction" className="live-reaction"><h3>Сиена наблюдает</h3><p>{sessionId?'Пока ничего важного не произошло.':'Ожидание игровой сессии.'}</p></Card>
}

export default function App(){
  const {state,events,setEvents,reactions,reactionGeneration,reactionProvider,scene,voiceStatus,voiceGeneration,voiceReady,voiceClips,presenceStatus,command,status,bridge,socketState,sendCommand}=useObserver()
  const [enabled,setEnabled]=useState<Set<Priority>>(new Set(priorities))
  const [error,setError]=useState('')
  const [fullHistory,setFullHistory]=useState(false)
  const [now,setNow]=useState(Date.now())
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[])
  const filtered=useMemo(()=>events.filter(event=>enabled.has(event.priority)),[events,enabled])
  const sessionId=state?.session_id??status.active_session
  const voice=useVoicePlayback({clips:voiceReady,generation:voiceGeneration,sessionId,status:voiceStatus})
  const sessionReactions=useMemo(()=>reactions.filter(item=>item.session_id===sessionId),[reactions,sessionId])
  const liveReaction=selectLiveReaction(reactions,sessionId,now)
  const lifecycle=reactionGeneration?.session_id===sessionId?reactionGeneration:null
  const sessionEnded=events.find(item=>item.session_id===sessionId)?.event_type==='session_ended'
  const showLifecycle=lifecycleCanReplace(liveReaction,lifecycle,events,now)
  const visibleHistory=fullHistory?sessionReactions:sessionReactions.slice(0,HISTORY_PREVIEW)
  const toggle=(priority:Priority)=>setEnabled(old=>{const next=new Set(old);next.has(priority)?next.delete(priority):next.add(priority);return next})
  const execute=async(intent:Intent)=>{setError('');try{await sendCommand(intent)}catch(reason){setError(reason instanceof Error?reason.message:'Command failed')}}
  const age=status.last_packet_at?Math.max(0,Math.round((Date.now()-new Date(status.last_packet_at).getTime())/1000))+'s ago':'never'
  const capabilityValue=(capability:keyof BridgeCapabilities,value:boolean|undefined)=>state?.source==='cet'&&bridge&&!bridge.capabilities[capability]?'Unavailable':yes(value??false)
  const deep=state?.deep_game_state
  const deepHealth=formatResource(deep?.stat_pools?.current_health,deep?.stat_pools?.maximum_health)
  const deepRam=formatResource(deep?.stat_pools?.current_memory,deep?.stat_pools?.maximum_memory)
  const weaponName=shortenWeaponRecord(deep?.weapon?.record_id)
  const cyberdeck=formatCyberdeck(deep?.cyberdeck,deep?.capabilities?.cyberdeck_identity)

  return <main>
    <header><div><p className="eyebrow">NIGHT CITY TELEMETRY LINK · V0.8.4 READ-ONLY</p><h1>Siena Cyberpunk Companion</h1></div><div className="status-strip"><span className={`dot ${socketState}`}/><b>WS {socketState}</b><span>BACKEND {status.backend}</span><b className="source">{state?.source==='cet'?'CYBERPUNK CET':'SIMULATOR'}</b><span>SESSION {sessionId??'—'}</span><span>PACKET {age}</span></div></header>
    {bridge?.source_conflict&&<div className="conflict">SOURCE CONFLICT · simulator and CET are both sending telemetry. Active source: {bridge.active_source.toUpperCase()}.</div>}
    {!state&&<div className="offline">Waiting for telemetry. The panel remains available while the backend or telemetry source is offline.</div>}
    <div className="grid">
      <Card title="Telemetry"><Row label="Running" value={yes(state?.game.running??false)}/><Row label="Loaded" value={yes(state?.game.loaded??false)}/><Row label="Paused" value={capabilityValue('pause_state',state?.game.paused)}/><Row label="District" value={state?.source==='cet'&&bridge&&!bridge.capabilities.district?'Unavailable':state?.environment.district??'—'}/></Card>
      <Card title="Player"><div className="meter"><i style={{width:`${state?percent(state.player.health,state.player.max_health):0}%`}}/></div><Row label="Health" value={state?`${state.player.health} / ${state.player.max_health} (${percent(state.player.health,state.player.max_health)}%)`:'—'} hot={!!state&&percent(state.player.health,state.player.max_health)<=25}/><Row label="Combat" value={capabilityValue('combat_state',state?.player.in_combat)}/><Row label="Vehicle" value={capabilityValue('vehicle_state',state?.player.in_vehicle)}/><Row label="Position" value={state?`${state.player.position.x.toFixed(1)}, ${state.player.position.y.toFixed(1)}, ${state.player.position.z.toFixed(1)}`:'—'}/></Card>
      <Card title="Deep Game State"><Row label="Health" value={deepHealth.text} hot={deepHealth.percent!=null&&deepHealth.percent<=25}/><Row label="RAM / Memory" value={deepRam.text} hot={deepRam.percent!=null&&deepRam.percent<=25}/><Row label="Weapon" value={weaponName==='—'?'—':`${weaponName} · ${deep?.weapon?.drawn?'drawn':'holstered'}`}/><Row label="Status effects" value={deep?.status_effects?.observed_count??'—'}/><Row label="Level / Street Cred" value={deep?.stats?.level!=null||deep?.stats?.street_cred!=null?`${deep?.stats?.level??'—'} / ${deep?.stats?.street_cred??'—'}`:'—'}/><Row label="Armor" value={deep?.stats?.armor??'—'}/><Row label="Cyberdeck" value={cyberdeck.identity}/><Row label="Deck quality" value={cyberdeck.quality}/><Row label="Programs used / total" value={cyberdeck.capacity}/>{cyberdeck.programs.map(program=><Row key={`${program.slot}:${program.record}`} label={`Quickhack slot ${program.slot}`} value={program.record}/>)}{cyberdeck.truncated&&<p className="hint">Quickhack list truncated to the safe limit.</p>}</Card>
      <Card title="Current Scene"><SceneTags phase={scene?.phase} focus={liveReaction?.focus??lifecycle?.focus}/><Row label="State" value={scene?.summary??'Waiting for a meaningful scene'}/><Row label="Severity" value={scene?.severity??'—'} hot={scene?.severity==='critical'}/><Row label="Health trend" value={scene?.health_trend?.replaceAll('_',' ')??'—'}/><Row label="Reactions" value={scene?.reaction_count??0}/></Card>
      <Card title="Companion"><Row label="Present" value={yes(state?.companion.present??false)}/><Row label="Health" value={state?`${state.companion.health} / ${state.companion.max_health}`:'—'}/><Row label="Distance" value={state?`${state.companion.distance_to_player.toFixed(1)} m`:'—'} hot={(state?.companion.distance_to_player??0)>20}/><Row label="Moving" value={yes(state?.companion.moving??false)}/><Row label="Intent" value={state?.companion.current_intent??'—'}/><Row label="Stuck" value={yes(state?.derived?.companion_stuck??false)} hot={state?.derived?.companion_stuck}/></Card>
      <Card title="Reaction Planner"><Row label="Enabled" value={status.planner?.enabled?'YES':'NO'}/><Row label="Provider" value={status.planner?.provider??'template'}/><Row label="Events / reactions" value={`${status.planner?.event_count??events.length} / ${status.planner?.reaction_count??reactions.length}`}/><Row label="Cooldown" value={`${Math.ceil(status.planner?.cooldown_remaining_seconds??0)}s`}/></Card>
      <Card title="Siena Core Status"><Row label="Configured / active" value={`${reactionProvider?.configured_provider??'template'} / ${reactionProvider?.active_provider??'template'}`}/><Row label="Core" value={reactionProvider?.configuration_error?'Configuration error':reactionProvider?.siena_core_reachable===true?'ONLINE':reactionProvider?.siena_core_reachable===false?'OFFLINE':'Not probed'} hot={reactionProvider?.siena_core_reachable===false||!!reactionProvider?.configuration_error}/><Row label="Circuit" value={reactionProvider?.circuit_state??'closed'} hot={reactionProvider?.circuit_state==='open'}/><Row label="Queue" value={`${reactionProvider?.queue_size??0} / ${reactionProvider?.queue_capacity??0}`}/><Row label="Last latency" value={reactionProvider?.average_latency_ms!=null?`${Math.round(reactionProvider.average_latency_ms)} ms`:'—'}/><Row label="Fallbacks" value={reactionProvider?.fallback_count??0}/>{reactionProvider?.last_error&&<details><summary>Diagnostics</summary><p className="error">{reactionProvider.last_error}</p></details>}</Card>
      <Card title="Voice Status"><Row label="Backend voice" value={voiceStatus?.enabled?'ENABLED':'TEXT ONLY'}/><Row label="Playback" value={voice.state.replaceAll('_',' ')}/><Row label="Role" value={voice.isLeader?'LEADER':'FOLLOWER'}/><Row label="TTS" value={voiceStatus?.tts_reachable===true?'READY':voiceStatus?.tts_reachable===false?'UNAVAILABLE':'NOT PROBED'} hot={voiceStatus?.tts_reachable===false}/><Row label="Provider / speaker" value={`${voiceStatus?.tts_provider??'—'} / ${voiceStatus?.speaker??'default'}`}/><Row label="Circuit" value={voiceStatus?.circuit_state??'closed'} hot={voiceStatus?.circuit_state==='open'}/><Row label="Backend / playback queue" value={`${voiceStatus?.queue_size??0} / ${voice.queue.length}`}/><Row label="Last latency" value={voiceStatus?.average_latency_ms!=null?`${Math.round(voiceStatus.average_latency_ms)} ms`:'—'}/><div className="voice-controls">{!voice.enabled||!voice.unlocked?<button onClick={()=>void voice.enable()}>Включить голос</button>:<button onClick={voice.disable}>Выключить голос</button>}<button onClick={voice.toggleMute}>{voice.muted?'Unmute':'Mute'}</button><button onClick={voice.clearQueue}>Очистить очередь</button><label>Volume {Math.round(voice.volume*100)}%<input type="range" min="0" max="1" step="0.05" value={voice.volume} onChange={event=>voice.setVolume(Number(event.target.value))}/></label></div>{voice.error&&<p className="error">{voice.error}</p>}{voiceStatus?.last_error&&<details><summary>Voice diagnostics</summary><p className="error">{voiceStatus.last_error}</p></details>}</Card>
      <Card title="In-Game Presence"><Row label="Backend projection" value={presenceStatus?.enabled?'ENABLED':'DISABLED'}/><Row label="State / revision" value={`${presenceStatus?.state??'hidden'} / ${presenceStatus?.revision??0}`}/><Row label="CET consumer" value={presenceStatus?.consumer_connected?'CONNECTED':'NOT POLLING'} hot={!!presenceStatus?.enabled&&!presenceStatus.consumer_connected}/><Row label="Last poll" value={presenceStatus?.last_poll_at?new Date(presenceStatus.last_poll_at).toLocaleTimeString():'never'}/><Row label="Last sent" value={presenceStatus?.last_revision_sent??'—'}/><Row label="Overlay" value={presenceStatus?.overlay_supported===true?(presenceStatus.overlay_enabled?'ENABLED LOCALLY':'DISABLED LOCALLY'):'NOT REPORTED'}/><Row label="Cyrillic font" value={presenceStatus?.font_cyrillic_ready===true?'CONFIRMED':'UNCONFIRMED'}/>{presenceStatus?.current_text_preview&&<p className="hint">{presenceStatus.current_text_preview}</p>}{presenceStatus?.last_error&&<p className="error">{presenceStatus.last_error}</p>}</Card>
      <Card title="Bridge Status"><Row label="Status" value={bridge?.connected?'CONNECTED':'DISCONNECTED'} hot={!!bridge&&!bridge.connected}/><Row label="Bridge / protocol" value={bridge?`${bridge.bridge_version??'—'} / ${bridge.protocol_version??'—'}`:'—'}/><Row label="Game / CET" value={bridge?`${bridge.game_version??'—'} / ${bridge.cet_version??'—'}`:'—'}/><Row label="Session / sequence" value={bridge?.session_id?`${bridge.session_id} / ${bridge.last_sequence??'—'}`:'—'}/><Row label="Last telemetry" value={bridge?.last_telemetry_at?new Date(bridge.last_telemetry_at).toLocaleTimeString():'never'}/><Row label="Latency / rate" value={bridge?`${bridge.latency_ms?.toFixed(0)??'—'} ms / ${bridge.telemetry_rate.toFixed(2)} Hz`:'—'}/><details><summary>Capabilities</summary><Row label="Health" value={bridge?.capabilities.player_health?'Available':'Unavailable'}/><Row label="Position" value={bridge?.capabilities.player_position?'Available':'Unavailable'}/><Row label="Combat" value={bridge?.capabilities.combat_state?'Available':'Unavailable'}/><Row label="Vehicle" value={bridge?.capabilities.vehicle_state?'Available':'Unavailable'}/><Row label="Pause" value={bridge?.capabilities.pause_state?'Available':'Unavailable'}/><Row label="District" value={bridge?.capabilities.district?'Available':'Unavailable'}/></details>{bridge?.last_error&&<p className="error">{bridge.last_error}</p>}</Card>
    </div>
    <div className="lower">
      <Card title="Game Events"><div className="toolbar">{priorities.map(p=><button key={p} className={enabled.has(p)?'selected':''} onClick={()=>toggle(p)}>{p.slice(0,2)}</button>)}<button onClick={()=>setEvents([])}>Clear local</button><span>{filtered.length} / 200</span></div><div className="events">{filtered.length===0&&<p className="empty">No meaningful game events yet.</p>}{filtered.map(event=><article key={event.event_id} className={event.priority}><time>{new Date(event.created_at).toLocaleTimeString()}</time><div><b>{event.event_type}</b><small>{event.severity} · {event.source}</small></div><div><span>{event.summary}</span><code>{JSON.stringify(event.payload)}</code><details><summary>Diagnostics</summary><code>{event.session_id} · seq {event.sequence??'—'}</code></details></div></article>)}</div></Card>
      <div className="side">
        <LiveReaction sessionId={sessionId} reaction={liveReaction} lifecycle={lifecycle} provider={reactionProvider} showLifecycle={showLifecycle} sessionEnded={sessionEnded} scene={scene} voiceGeneration={voiceGeneration} playingVoice={voice.current}/>
        <details className="card history-card"><summary>Voice Clips · diagnostic history</summary><div className="reactions">{voiceClips.length===0&&<p className="empty">No voice clips yet.</p>}{voiceClips.slice(0,10).map(clip=><article key={clip.voice_clip_id} className={clip.priority}><p>{String(clip.metadata.text_preview??clip.reaction_id)}</p><small>{clip.state} · {clip.tts_provider} · {clip.speaker??'default'} · {clip.duration_ms} ms audio · {clip.latency_ms==null?'—':`${Math.round(clip.latency_ms)} ms synthesis`}</small>{clip.error_category&&<p className="error">{clip.error_category}</p>}</article>)}</div></details>
        <details className="card history-card"><summary>Siena Reactions · diagnostic history</summary><div className="history-toolbar"><span>{sessionReactions.length} in current session</span>{sessionReactions.length>HISTORY_PREVIEW&&<button onClick={()=>setFullHistory(value=>!value)}>{fullHistory?'Show recent':'Show full local history'}</button>}</div><div className="reactions">{visibleHistory.length===0&&<p className="empty">No Siena reactions yet.</p>}{visibleHistory.map(reaction=><article key={reaction.reaction_id} className={reaction.priority}><p>{reaction.text}</p><small>{new Date(reaction.created_at).toLocaleTimeString()} · {reaction.event_type} · {reaction.provider}{reaction.model?` · ${reaction.model}`:''}{reaction.latency_ms!=null?` · ${Math.round(reaction.latency_ms)} ms`:''}</small>{reaction.fallback_used&&<span className="fallback-badge">TEMPLATE FALLBACK</span>}<details><summary>Diagnostics</summary><code>{reaction.fallback_reason??'core response'} · {reaction.request_id??'no request id'}</code></details></article>)}</div></details>
        <Card title="Legacy Display-only Decisions"><Row label="Command" value={command?.intent??'continue'}/><Row label="Priority" value={command?.priority??'P3_LOW'}/><p className="hint">These compatibility decisions are never sent to Cyberpunk.</p><div className="commands">{intents.map(intent=><button key={intent} onClick={()=>void execute(intent)}>{intent}</button>)}</div>{error&&<p className="error">{error}</p>}</Card>
        <details className="card"><summary>Debug · latest JSON</summary><pre>{JSON.stringify(state,null,2)}</pre></details>
      </div>
    </div>
  </main>
}
