import {useMemo,useState} from 'react'
import {useObserver} from './useObserver'
import type {BridgeCapabilities,Intent,Priority} from './types'

const priorities:Priority[]=['P0_CRITICAL','P1_HIGH','P2_MEDIUM','P3_LOW']
const intents:Intent[]=['follow','hold','regroup','protect','retreat','stop']
const yes=(value:boolean)=>value?'YES':'NO'
const percent=(value:number,max:number)=>Math.round(value/max*100)

function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="card"><h2>{title}</h2>{children}</section>}
function Row({label,value,hot=false}:{label:string;value:React.ReactNode;hot?:boolean}){return <div className="row"><span>{label}</span><strong className={hot?'hot':''}>{value}</strong></div>}

export default function App(){
  const {state,events,setEvents,reactions,command,status,bridge,socketState,sendCommand}=useObserver()
  const [enabled,setEnabled]=useState<Set<Priority>>(new Set(priorities))
  const [error,setError]=useState('')
  const filtered=useMemo(()=>events.filter(event=>enabled.has(event.priority)),[events,enabled])
  const toggle=(priority:Priority)=>setEnabled(old=>{const next=new Set(old);next.has(priority)?next.delete(priority):next.add(priority);return next})
  const execute=async(intent:Intent)=>{setError('');try{await sendCommand(intent)}catch(reason){setError(reason instanceof Error?reason.message:'Command failed')}}
  const age=status.last_packet_at?Math.max(0,Math.round((Date.now()-new Date(status.last_packet_at).getTime())/1000))+'s ago':'never'
  const capabilityValue=(capability:keyof BridgeCapabilities,value:boolean|undefined)=>state?.source==='cet'&&bridge&&!bridge.capabilities[capability]?'Unavailable':yes(value??false)
  return <main>
    <header><div><p className="eyebrow">NIGHT CITY TELEMETRY LINK · V0.3 READ-ONLY</p><h1>Siena Cyberpunk Companion</h1></div><div className="status-strip"><span className={`dot ${socketState}`}/><b>WS {socketState}</b><span>BACKEND {status.backend}</span><b className="source">{state?.source==='cet'?'CYBERPUNK CET':'SIMULATOR'}</b><span>SESSION {state?.session_id??'—'}</span><span>PACKET {age}</span></div></header>
    {bridge?.source_conflict&&<div className="conflict">SOURCE CONFLICT · simulator and CET are both sending telemetry. Active source: {bridge.active_source.toUpperCase()}.</div>}
    {!state&&<div className="offline">Waiting for telemetry. The panel remains available while the backend or telemetry source is offline.</div>}
    <div className="grid">
      <Card title="Game"><Row label="Running" value={yes(state?.game.running??false)}/><Row label="Loaded" value={yes(state?.game.loaded??false)}/><Row label="Paused" value={capabilityValue('pause_state',state?.game.paused)}/><Row label="District" value={state?.source==='cet'&&bridge&&!bridge.capabilities.district?'Unavailable':state?.environment.district??'—'}/></Card>
      <Card title="Player"><div className="meter"><i style={{width:`${state?percent(state.player.health,state.player.max_health):0}%`}}/></div><Row label="Health" value={state?`${state.player.health} / ${state.player.max_health} (${percent(state.player.health,state.player.max_health)}%)`:'—'} hot={!!state&&percent(state.player.health,state.player.max_health)<=25}/><Row label="Combat" value={capabilityValue('combat_state',state?.player.in_combat)}/><Row label="Vehicle" value={capabilityValue('vehicle_state',state?.player.in_vehicle)}/><Row label="Position" value={state?`${state.player.position.x.toFixed(1)}, ${state.player.position.y.toFixed(1)}, ${state.player.position.z.toFixed(1)}`:'—'}/></Card>
      <Card title="Companion"><Row label="Present" value={yes(state?.companion.present??false)}/><Row label="Health" value={state?`${state.companion.health} / ${state.companion.max_health}`:'—'}/><Row label="Distance" value={state?`${state.companion.distance_to_player.toFixed(1)} m`:'—'} hot={(state?.companion.distance_to_player??0)>20}/><Row label="Moving" value={yes(state?.companion.moving??false)}/><Row label="Intent" value={state?.companion.current_intent??'—'}/><Row label="Stuck" value={yes(state?.derived?.companion_stuck??false)} hot={state?.derived?.companion_stuck}/></Card>
      <Card title="Reaction Planner"><Row label="Enabled" value={status.planner?.enabled?'YES':'NO'}/><Row label="Provider" value={status.planner?.provider??'template'}/><Row label="Events / reactions" value={`${status.planner?.event_count??events.length} / ${status.planner?.reaction_count??reactions.length}`}/><Row label="Cooldown" value={`${Math.ceil(status.planner?.cooldown_remaining_seconds??0)}s`}/></Card>
      <Card title="Cyberpunk Bridge"><Row label="Status" value={bridge?.connected?'CONNECTED':'DISCONNECTED'} hot={!!bridge&&!bridge.connected}/><Row label="Bridge / protocol" value={bridge?`${bridge.bridge_version??'—'} / ${bridge.protocol_version??'—'}`:'—'}/><Row label="Game / CET" value={bridge?`${bridge.game_version??'—'} / ${bridge.cet_version??'—'}`:'—'}/><Row label="Session / sequence" value={bridge?.session_id?`${bridge.session_id} / ${bridge.last_sequence??'—'}`:'—'}/><Row label="Last telemetry" value={bridge?.last_telemetry_at?new Date(bridge.last_telemetry_at).toLocaleTimeString():'never'}/><Row label="Latency / rate" value={bridge?`${bridge.latency_ms?.toFixed(0)??'—'} ms / ${bridge.telemetry_rate.toFixed(2)} Hz`:'—'}/><Row label="Health" value={bridge?.capabilities.player_health?'Available':'Unavailable'}/><Row label="Position" value={bridge?.capabilities.player_position?'Available':'Unavailable'}/><Row label="Combat" value={bridge?.capabilities.combat_state?'Available':'Unavailable'}/><Row label="Vehicle" value={bridge?.capabilities.vehicle_state?'Available':'Unavailable'}/><Row label="Pause" value={bridge?.capabilities.pause_state?'Available':'Unavailable'}/><Row label="District" value={bridge?.capabilities.district?'Available':'Unavailable'}/>{bridge?.last_error&&<p className="error">{bridge.last_error}</p>}</Card>
    </div>
    <div className="lower">
      <Card title="Game Events"><div className="toolbar">{priorities.map(p=><button key={p} className={enabled.has(p)?'selected':''} onClick={()=>toggle(p)}>{p.slice(0,2)}</button>)}<button onClick={()=>setEvents([])}>Clear local</button><span>{filtered.length} / 200</span></div><div className="events">{filtered.length===0&&<p className="empty">No meaningful game events yet.</p>}{filtered.map(event=><article key={event.event_id} className={event.priority}><time>{new Date(event.created_at).toLocaleTimeString()}</time><div><b>{event.event_type}</b><small>{event.severity} · {event.source}</small></div><div><span>{event.summary}</span><code>{JSON.stringify(event.payload)}</code><details><summary>Diagnostics</summary><code>{event.session_id} · seq {event.sequence??'—'}</code></details></div></article>)}</div></Card>
      <div className="side"><Card title="Siena Reactions"><div className="reactions">{reactions.length===0&&<p className="empty">No Siena reactions yet.</p>}{reactions.map(reaction=><article key={reaction.reaction_id} className={reaction.priority}><p>{reaction.text}</p><small>{new Date(reaction.created_at).toLocaleTimeString()} · {reaction.priority} · {reaction.provider}</small><code>{reaction.event_type}</code></article>)}</div></Card><Card title="Legacy Display-only Decisions"><Row label="Command" value={command?.intent??'continue'}/><Row label="Priority" value={command?.priority??'P3_LOW'}/><p className="hint">These compatibility decisions are never sent to Cyberpunk.</p><div className="commands">{intents.map(intent=><button key={intent} onClick={()=>void execute(intent)}>{intent}</button>)}</div>{error&&<p className="error">{error}</p>}</Card><details className="card"><summary>Debug · latest JSON</summary><pre>{JSON.stringify(state,null,2)}</pre></details></div>
    </div>
  </main>
}
