export type Priority = 'P0_CRITICAL'|'P1_HIGH'|'P2_MEDIUM'|'P3_LOW'
export type Severity = 'info'|'low'|'medium'|'high'|'critical'
export type Intent = 'continue'|'follow'|'hold'|'regroup'|'protect'|'retreat'|'stop'
export type NpcCommandName='spawn'|'despawn'|'follow'|'stay'|'come_here'|'look_at_player'|'clear_look_at'|'status'
export interface NpcStatus {enabled:boolean;backend_connected:boolean|null;player_available:boolean|null;dynamic_entity_system_ready:boolean|null;entity_exists:boolean|null;managed:boolean|null;spawned:boolean|null;resolved:boolean|null;runtime_class:string|null;entity_record:string;appearance:string;current_appearance:string|null;temporary_appearance:boolean;temporary_body_record:string;lifecycle_state:string|null;requested_mode:string|null;effective_mode:string|null;mode:string|null;movement_active:boolean|null;look_at_active:boolean|null;stuck:boolean|null;rescue_state:string|null;conversation_state:string|null;active_utterance_id:string|null;subtitle_visible:boolean|null;suspended_reason:string|null;last_command:NpcCommandName|null;last_command_result:string|null;last_command_completed_at:string|null;last_error:string|null;cleanup_reason:string|null}
export interface EmbodimentSettings {npc_presence_enabled:boolean;npc_auto_spawn:boolean;npc_auto_follow:boolean;npc_spawn_delay_seconds:number;npc_follow_distance:number;npc_return_distance:number;npc_rescue_distance:number;npc_rescue_enabled:boolean;npc_suspend_during_combat:boolean;npc_suspend_in_vehicle:boolean;npc_in_game_subtitles_enabled:boolean;npc_voice_embodiment_enabled:boolean}
export type BuildStyle='no_cyberdeck'|'cyberdeck_unknown'|'offensive_netrunner'|'control_netrunner'|'recon_netrunner'|'mixed_netrunner'|'unknown'
export interface BuildProfile {profile_version:'0.8.5';operating_system:{kind:'cyberdeck';record_id:string|null;quality:string|null;iconic:boolean|null}|null;quickhack_loadout:{installed:number|null;capacity:number|null;fill_percent:number|null;known_programs:number|null;unknown_programs:number|null;categories:{offensive:number;control:number;recon:number;utility:number;unknown:number}|null;dominant_category:'offensive'|'control'|'recon'|'utility'|'unknown'|null;style:BuildStyle|null;confidence:number|null}|null;resources:{health_maximum:number|null;ram_maximum:number|null;armor:number|null}|null;current_weapon_record_id:string|null;summary_key:BuildStyle|null;confidence:number|null;evidence:string[];limitations:string[]}

export interface DeepGameState {
  capabilities:{player:boolean|null;stats:boolean|null;stat_pools:boolean|null;weapon:boolean|null;status_effects:boolean|null;cyberdeck_identity?:boolean|null;cyberdeck_metadata?:boolean|null;cyberdeck_programs?:boolean|null;cyberdeck_capacity?:boolean|null}|null
  player:{entity_available:boolean|null;session_available:boolean|null;is_pre_game:boolean|null;position:{x:number;y:number;z:number}|null;mounted_vehicle:boolean|null}|null
  stats:{level:number|null;street_cred:number|null;armor:number|null;power_level:number|null;health:number|null;memory:number|null}|null
  stat_pools:{current_health:number|null;maximum_health:number|null;current_memory:number|null;maximum_memory:number|null}|null
  weapon:{drawn:boolean|null;record_id:string|null;source:'active'|'weapon_right'|'none'|null}|null
  status_effects:{observed_count:number|null;truncated:boolean|null;limit:number|null}|null
  cyberdeck?:{record_id:string|null;quality:string|null;iconic:boolean|null;tags:('Cyberdeck'|'Cyberware'|'Iconic_OS_CW')[]|null;program_capacity:{used:number|null;empty:number|null;total:number|null}|null;programs:{slot_id:string;record_id:string;quality:string|null;iconic:boolean|null}[]|null;truncated:boolean|null}|null
  build_profile?:BuildProfile|null
}

export interface GameState {
  schema_version:string; session_id:string; sequence:number; captured_at:string;source:'simulator'|'cet';bridge_version:string|null
  game:{running:boolean;loaded:boolean;paused:boolean}
  player:{health:number;max_health:number;in_combat:boolean;in_vehicle:boolean;position:{x:number;y:number;z:number}}
  companion:{present:boolean;health:number;max_health:number;distance_to_player:number;current_intent:string;moving:boolean}
  environment:{district:string;visible_hostiles:number;highest_threat_id:string|null}
  deep_game_state?:DeepGameState|null
  derived?:{companion_stuck:boolean}
}
export interface GameEvent {event_id:string;session_id:string;event_type:string;priority:Priority;severity:Severity;created_at:string;source:string;sequence:number|null;summary:string;deduplication_key:string;payload:Record<string,unknown>}
export type ScenePhase='session_start'|'exploration'|'combat'|'danger'|'recovery'|'vehicle'|'idle'|'transition'|'session_end'|'unknown'
export type ReactionFocus='session_greeting'|'danger_warning'|'combat_comment'|'recovery_comment'|'exploration_comment'|'vehicle_comment'|'idle_comment'|'scene_resolution'|'ram_warning'|'resource_recovery'|'equipment_change'
export interface SceneContext {scene_id:string;session_id:string;phase:ScenePhase;previous_phase:ScenePhase|null;severity:Severity;peak_severity:Severity;health_current:number|null;health_max:number|null;health_maximum:number|null;health_percent:number|null;health_state:'normal'|'low'|'critical'|null;health_trend:string;ram_current:number|null;ram_maximum:number|null;ram_percent:number|null;ram_state:'normal'|'low'|'exhausted'|null;active_weapon_record_id:string|null;weapon_drawn:boolean|null;status_effect_count:number|null;level:number|null;street_cred:number|null;armor:number|null;cyberdeck_record_id:string|null;cyberdeck_quality:string|null;cyberdeck_iconic:boolean|null;cyberdeck_program_count:number|null;cyberdeck_program_capacity:number|null;installed_quickhack_record_ids:string[];build_style?:BuildStyle|null;build_confidence?:number|null;quickhack_dominant_category?:string|null;quickhack_known_count?:number|null;quickhack_unknown_count?:number|null;quickhack_category_counts?:Record<string,number>|null;build_evidence?:string[];build_limitations?:string[];player_available:boolean|null;session_available:boolean|null;is_pre_game:boolean|null;combat_state:boolean|null;vehicle_state:boolean|null;summary:string;revision:number;reaction_count:number;started_at:string;updated_at:string;closed_at:string|null}
export type VoiceState='queued'|'synthesizing'|'ready'|'playing'|'completed'|'suppressed'|'failed'|'cancelled'
export type VoicePriority='info'|'low'|'medium'|'high'|'critical'
export interface VoiceGenerationStatus {voice_request_id:string;reaction_id:string;session_id:string;scene_id:string|null;state:VoiceState;priority:VoicePriority;reason:string|null;created_at:string}
export interface VoiceClipReady {voice_clip_id:string;voice_request_id:string;reaction_id:string;session_id:string;scene_id:string|null;scene_revision:number|null;focus:ReactionFocus|null;priority:VoicePriority;audio_url:string;content_type:string;duration_ms:number;tts_provider:string;speaker:string|null;expires_at:string}
export interface VoiceClip {voice_clip_id:string;voice_request_id:string;reaction_id:string;session_id:string;scene_id:string|null;scene_revision:number|null;focus:ReactionFocus|null;priority:VoicePriority;state:VoiceState;audio_format:'wav';content_type:string;sample_rate:number;channels:number;duration_ms:number;byte_length:number;created_at:string;expires_at:string;tts_provider:string;speaker:string|null;language:string;latency_ms:number|null;error_category:string|null;metadata:Record<string,unknown>}
export interface VoiceStatus {enabled:boolean;muted:boolean;configured:boolean;tts_base_url:'configured'|'not_configured';tts_reachable:boolean|null;tts_provider:string|null;speaker:string|null;language:string;interrupt_mode:'never'|'critical_only';post_play_gap_ms:number;circuit_state:'closed'|'open'|'half_open';consecutive_failures:number;worker_running:boolean;queue_size:number;queue_capacity:number;clip_count:number;currently_synthesizing:string|null;last_request_at:string|null;last_success_at:string|null;last_failure_at:string|null;last_error:string|null;average_latency_ms:number|null;suppressed_count:number;failed_count:number}
export type InGamePresenceState='hidden'|'queued'|'generating'|'reaction'|'fallback'|'voice_synthesizing'|'voice_playing'|'unavailable'
export interface InGamePresenceStatus {enabled:boolean;active:boolean;revision:number;state:InGamePresenceState;consumer_connected:boolean;last_poll_at:string|null;last_revision_sent:number|null;poll_count:number;unchanged_count:number;last_error:string|null;current_text_preview:string;overlay_supported:boolean|null;overlay_enabled:boolean|null;overlay_version:string|null;font_cyrillic_ready:boolean|null;poll_interval_ms:number}
export interface SienaReaction {reaction_id:string;event_id:string;session_id:string|null;event_type:string;text:string;created_at:string;priority:'low'|'medium'|'high'|'critical';provider:string;requested_provider:string|null;fallback_used:boolean;fallback_reason:string|null;latency_ms:number|null;model:string|null;request_id:string|null;scene_id:string|null;scene_revision:number|null;scene_phase:ScenePhase|null;focus:ReactionFocus|null;metadata:Record<string,unknown>}
export type ReactionGenerationState = 'queued'|'generating'|'completed'|'fallback'|'suppressed'|'failed'
export interface ReactionGenerationStatus {request_id:string;event_id:string;session_id:string;event_type:string;state:ReactionGenerationState;scene_id:string|null;scene_phase:ScenePhase|null;focus:ReactionFocus|null;reason:string|null}
export interface PlannerStatus {enabled:boolean;provider:string;queued_events:number;event_count:number;reaction_count:number;last_event_at:string|null;last_reaction_at:string|null;cooldown_remaining_seconds:number}
export interface ReactionProviderStatus {enabled:boolean;configured_provider:string;active_provider:string;fallback_provider:string;configuration_error:string|null;siena_core_reachable:boolean|null;circuit_state:'closed'|'open'|'half_open';consecutive_failures:number;queue_size:number;queue_capacity:number;worker_running:boolean;last_request_at:string|null;last_success_at:string|null;last_failure_at:string|null;last_error:string|null;average_latency_ms:number|null;fallback_count:number;stale_suppressed_count:number}
export interface ContextualCompanionStatus {enabled:boolean;session_id:string|null;situation_state:'unavailable'|'loading'|'idle'|'exploration'|'driving'|'combat'|'danger'|'recovery';reaction_urgency:'none'|'context'|'recovery'|'warning'|'critical';primary_pending_event:string|null;grouped_related_events:string[];queue_size:number;last_emitted_reaction_category:string|null;last_suppression_reason:string|null;event_window_size:number}
export interface Command {command_id:string;intent:Intent;priority:Priority;created_at:string;valid_for_seconds:number;target_id:null;parameters:Record<string,unknown>;source:string}
export interface BridgeCapabilities {player_health:boolean;player_position:boolean;combat_state:boolean;vehicle_state:boolean;pause_state:boolean;district:boolean;deep_player:boolean;deep_stats:boolean;deep_stat_pools:boolean;deep_weapon:boolean;deep_status_effects:boolean;cyberdeck_identity:boolean;cyberdeck_metadata:boolean;cyberdeck_programs:boolean;cyberdeck_capacity:boolean;presence_overlay_supported:boolean|null;presence_overlay_enabled:boolean|null;presence_overlay_version:string|null;presence_font_cyrillic_ready:boolean|null;presence_poll_interval_ms:number|null}
export interface BridgeStatus {connected:boolean;compatible:boolean;bridge_id:string|null;bridge_version:string|null;protocol_version:string|null;game_version:string|null;cet_version:string|null;last_hello_at:string|null;last_heartbeat_at:string|null;last_telemetry_at:string|null;last_sequence:number|null;session_id:string|null;capabilities:BridgeCapabilities;last_error:string|null;latency_ms:number|null;telemetry_rate:number;dropped_stale_states:number;source_conflict:boolean;active_source:'cet'|'simulator';configured_source:'auto'|'cet'|'simulator';registered_bridges:number}
export interface Status {backend:string;active_session:string|null;last_packet_at:string|null;active_source?:'cet'|'simulator';bridge?:BridgeStatus;planner?:PlannerStatus;reaction_provider?:ReactionProviderStatus;scene?:SceneContext|null;voice?:VoiceStatus;presence?:InGamePresenceStatus;contextual_companion?:ContextualCompanionStatus;npc?:NpcStatus;scheduler?:{mode:string;reason:string|null;command:Command|null}}
export type Envelope = {type:'state';data:GameState}|{type:'event'|'game_event';data:GameEvent;payload?:GameEvent}|{type:'siena_reaction';data:SienaReaction;payload?:SienaReaction}|{type:'reaction_generation_status';data:ReactionGenerationStatus;payload?:ReactionGenerationStatus}|{type:'reaction_provider_status';data:ReactionProviderStatus;payload?:ReactionProviderStatus}|{type:'scene_context_updated';data:SceneContext;payload?:SceneContext}|{type:'contextual_companion_status';data:ContextualCompanionStatus}|{type:'contextual_companion_trace';data:{trace_type:string;session_id:string|null;event_id:string|null;reason:string;created_at:string}}|{type:'voice_generation_status';data:VoiceGenerationStatus;payload?:VoiceGenerationStatus}|{type:'voice_clip_ready';data:VoiceClipReady;payload?:VoiceClipReady}|{type:'in_game_presence_status';data:InGamePresenceStatus;payload?:InGamePresenceStatus}|{type:'command';data:Command}|{type:'status';data:Status}|{type:'bridge_status';data:BridgeStatus}
