export type Priority = 'P0_CRITICAL'|'P1_HIGH'|'P2_MEDIUM'|'P3_LOW'
export type Severity = 'info'|'low'|'medium'|'high'|'critical'
export type Intent = 'continue'|'follow'|'hold'|'regroup'|'protect'|'retreat'|'stop'

export interface DeepGameState {
  capabilities:{player:boolean|null;stats:boolean|null;stat_pools:boolean|null;weapon:boolean|null;status_effects:boolean|null}|null
  player:{entity_available:boolean|null;session_available:boolean|null;is_pre_game:boolean|null;position:{x:number;y:number;z:number}|null;mounted_vehicle:boolean|null}|null
  stats:{level:number|null;street_cred:number|null;armor:number|null;power_level:number|null;health:number|null;memory:number|null}|null
  stat_pools:{current_health:number|null;maximum_health:number|null;current_memory:number|null;maximum_memory:number|null}|null
  weapon:{drawn:boolean|null;record_id:string|null;source:'active'|'weapon_right'|'none'|null}|null
  status_effects:{observed_count:number|null;truncated:boolean|null;limit:number|null}|null
}

export interface GameState {
  schema_version:string; session_id:string; sequence:number; captured_at:string;source:'simulator'|'cet';bridge_version:string|null
  game:{running:boolean;loaded:boolean;paused:boolean}
  player:{health:number;max_health:number;in_combat:boolean;in_vehicle:boolean;position:{x:number;y:number;z:number}}
  companion:{present:boolean;health:number;max_health:number;distance_to_player:number;current_intent:string;moving:boolean}
  environment:{district:string;visible_hostiles:number;highest_threat_id:string|null}
  deep_game_state?:DeepGameState|null
  derived?:{companion_stuck:boolean}
}
export interface GameEvent {event_id:string;session_id:string;event_type:string;priority:Priority;severity:Severity;created_at:string;source:string;sequence:number|null;summary:string;deduplication_key:string;payload:Record<string,unknown>}
export type ScenePhase='session_start'|'exploration'|'combat'|'danger'|'recovery'|'vehicle'|'idle'|'transition'|'session_end'|'unknown'
export type ReactionFocus='session_greeting'|'danger_warning'|'combat_comment'|'recovery_comment'|'exploration_comment'|'vehicle_comment'|'idle_comment'|'scene_resolution'
export interface SceneContext {scene_id:string;session_id:string;phase:ScenePhase;previous_phase:ScenePhase|null;severity:Severity;peak_severity:Severity;health_percent:number|null;health_trend:string;combat_state:boolean|null;vehicle_state:boolean|null;summary:string;revision:number;reaction_count:number;started_at:string;updated_at:string;closed_at:string|null}
export type VoiceState='queued'|'synthesizing'|'ready'|'playing'|'completed'|'suppressed'|'failed'|'cancelled'
export type VoicePriority='info'|'low'|'medium'|'high'|'critical'
export interface VoiceGenerationStatus {voice_request_id:string;reaction_id:string;session_id:string;scene_id:string|null;state:VoiceState;priority:VoicePriority;reason:string|null;created_at:string}
export interface VoiceClipReady {voice_clip_id:string;voice_request_id:string;reaction_id:string;session_id:string;scene_id:string|null;scene_revision:number|null;focus:ReactionFocus|null;priority:VoicePriority;audio_url:string;content_type:string;duration_ms:number;tts_provider:string;speaker:string|null;expires_at:string}
export interface VoiceClip {voice_clip_id:string;voice_request_id:string;reaction_id:string;session_id:string;scene_id:string|null;scene_revision:number|null;focus:ReactionFocus|null;priority:VoicePriority;state:VoiceState;audio_format:'wav';content_type:string;sample_rate:number;channels:number;duration_ms:number;byte_length:number;created_at:string;expires_at:string;tts_provider:string;speaker:string|null;language:string;latency_ms:number|null;error_category:string|null;metadata:Record<string,unknown>}
export interface VoiceStatus {enabled:boolean;muted:boolean;configured:boolean;tts_base_url:'configured'|'not_configured';tts_reachable:boolean|null;tts_provider:string|null;speaker:string|null;language:string;interrupt_mode:'never'|'critical_only';post_play_gap_ms:number;circuit_state:'closed'|'open'|'half_open';consecutive_failures:number;worker_running:boolean;queue_size:number;queue_capacity:number;clip_count:number;currently_synthesizing:string|null;last_request_at:string|null;last_success_at:string|null;last_failure_at:string|null;last_error:string|null;average_latency_ms:number|null;suppressed_count:number;failed_count:number}
export type InGamePresenceState='hidden'|'queued'|'generating'|'reaction'|'fallback'|'voice_synthesizing'|'voice_playing'|'unavailable'
export interface InGamePresenceStatus {enabled:boolean;active:boolean;revision:number;state:InGamePresenceState;consumer_connected:boolean;last_poll_at:string|null;last_revision_sent:number|null;poll_count:number;unchanged_count:number;last_error:string|null;current_text_preview:string;overlay_supported:boolean|null;overlay_enabled:boolean|null;overlay_version:string|null;font_cyrillic_ready:boolean|null;poll_interval_ms:number}
export interface SienaReaction {reaction_id:string;event_id:string;session_id:string|null;event_type:string;text:string;created_at:string;priority:'low'|'medium'|'high'|'critical';provider:string;requested_provider:string|null;fallback_used:boolean;fallback_reason:string|null;latency_ms:number|null;model:string|null;request_id:string|null;scene_id:string|null;scene_revision:number|null;scene_phase:ScenePhase|null;focus:ReactionFocus|null;metadata:Record<string,unknown>}
export type ReactionGenerationState = 'queued'|'generating'|'completed'|'fallback'|'suppressed'|'failed'
export interface ReactionGenerationStatus {request_id:string;event_id:string;session_id:string;event_type:string;state:ReactionGenerationState;scene_id:string|null;scene_phase:ScenePhase|null;focus:ReactionFocus|null;reason:string|null}
export interface PlannerStatus {enabled:boolean;provider:string;queued_events:number;event_count:number;reaction_count:number;last_event_at:string|null;last_reaction_at:string|null;cooldown_remaining_seconds:number}
export interface ReactionProviderStatus {enabled:boolean;configured_provider:string;active_provider:string;fallback_provider:string;configuration_error:string|null;siena_core_reachable:boolean|null;circuit_state:'closed'|'open'|'half_open';consecutive_failures:number;queue_size:number;queue_capacity:number;worker_running:boolean;last_request_at:string|null;last_success_at:string|null;last_failure_at:string|null;last_error:string|null;average_latency_ms:number|null;fallback_count:number;stale_suppressed_count:number}
export interface Command {command_id:string;intent:Intent;priority:Priority;created_at:string;valid_for_seconds:number;target_id:null;parameters:Record<string,unknown>;source:string}
export interface BridgeCapabilities {player_health:boolean;player_position:boolean;combat_state:boolean;vehicle_state:boolean;pause_state:boolean;district:boolean;deep_player:boolean;deep_stats:boolean;deep_stat_pools:boolean;deep_weapon:boolean;deep_status_effects:boolean;presence_overlay_supported:boolean|null;presence_overlay_enabled:boolean|null;presence_overlay_version:string|null;presence_font_cyrillic_ready:boolean|null;presence_poll_interval_ms:number|null}
export interface BridgeStatus {connected:boolean;compatible:boolean;bridge_id:string|null;bridge_version:string|null;protocol_version:string|null;game_version:string|null;cet_version:string|null;last_hello_at:string|null;last_heartbeat_at:string|null;last_telemetry_at:string|null;last_sequence:number|null;session_id:string|null;capabilities:BridgeCapabilities;last_error:string|null;latency_ms:number|null;telemetry_rate:number;dropped_stale_states:number;source_conflict:boolean;active_source:'cet'|'simulator';configured_source:'auto'|'cet'|'simulator';registered_bridges:number}
export interface Status {backend:string;active_session:string|null;last_packet_at:string|null;active_source?:'cet'|'simulator';bridge?:BridgeStatus;planner?:PlannerStatus;reaction_provider?:ReactionProviderStatus;scene?:SceneContext|null;voice?:VoiceStatus;presence?:InGamePresenceStatus;scheduler?:{mode:string;reason:string|null;command:Command|null}}
export type Envelope = {type:'state';data:GameState}|{type:'event'|'game_event';data:GameEvent;payload?:GameEvent}|{type:'siena_reaction';data:SienaReaction;payload?:SienaReaction}|{type:'reaction_generation_status';data:ReactionGenerationStatus;payload?:ReactionGenerationStatus}|{type:'reaction_provider_status';data:ReactionProviderStatus;payload?:ReactionProviderStatus}|{type:'scene_context_updated';data:SceneContext;payload?:SceneContext}|{type:'voice_generation_status';data:VoiceGenerationStatus;payload?:VoiceGenerationStatus}|{type:'voice_clip_ready';data:VoiceClipReady;payload?:VoiceClipReady}|{type:'in_game_presence_status';data:InGamePresenceStatus;payload?:InGamePresenceStatus}|{type:'command';data:Command}|{type:'status';data:Status}|{type:'bridge_status';data:BridgeStatus}
